version: '3.8'

networks:
  grpc_network:

services:
  rest:
    build: ./gRPCREST
    networks:
      - grpc_network
    restart: always
    ports:
      - 3030:3030
    environment:
      PORT: 3030
      HOST: "0.0.0.0"
      GRPC_SERVICE: "lb:4000"

  lb:
    build: ./gRPCBalancer
    networks:
      - grpc_network
    restart: always
    ports:
      - 4000:4000

  server1:
    build: ./gRPCGolang
    networks:
      - grpc_network
    restart: always
    ports:
      - 5000:5000
      - 6000:6000

  server2:
    build: ./gRPCGolang
    networks:
      - grpc_network
    restart: always
    ports:
      - 5001:5000
      - 6001:6000

  server3:
    build: ./gRPCGolang
    networks:
      - grpc_network
    restart: always
    ports:
      - 5002:5000
      - 6002:6000
